mainwindow: MainWindow.__init__
createGrooveGUI: createGrooveOptionsGUI()
mainwindow -> createGrooveGUI: calls
setGrooveText: Setting groove options combo box text
createGrooveGUI -> setGrooveText
createGrooveOptions: createGrooveOptions()
loadFromXML -> createGrooveGUI

