mainwindow: MainWindow.__init__()
createGrooveGUI: createGrooveOptionsGUI()
createGrooveOptions: createGrooveOptions()
setGrooveText: Setting groove options combo box text
guiCreation: Dynamic groove options form creation
loadFromXML: loadFromXML()


mainwindow -> createGrooveGUI: calls first
mainwindow -> createGrooveOptions: calls second
createGrooveGUI -> setGrooveText
createGrooveOptions -> setGrooveText
createGrooveOptions -> guiCreation
loadFromXML -> createGrooveGUI
loadFromXML -> createGrooveOptions
